# Generated by Django 5.0.7 on 2024-08-03 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedMemo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uploaded_file", models.FileField(upload_to="uploads/")),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("file_type", models.CharField(blank=True, max_length=50, null=True)),
                ("file_url", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Uploaded Memo",
                "verbose_name_plural": "Uploaded Memos",
                "unique_together": {("user", "file_name")},
            },
        ),
    ]
