# Generated by Django 5.0.7 on 2024-08-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedmemo",
            name="title",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
    ]
