# Generated by Django 5.0.7 on 2024-08-03 01:02

import django.utils.timezone
import src.core.models.aether_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="aetheruser",
            managers=[
                ("object", src.core.models.aether_user.AetherUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="aetheruser",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created_at"
            ),
        ),
    ]
