# Generated by Django 5.0.7 on 2024-08-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_aetheruser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="aetheruser",
            name="bio",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
